### ISSUE TITLE
Roadmap to `v0.1`

### ISSUE THREAD

**Issue by maltezfaria** [maltezfaria/LevelSetMethods.jl#34]
Things to polish/finish prior to release:

### Usage
- [x] Streamline how boundary conditions are passed to the `LevelSetEquation` constructor. Example that should work: #35  
```julia
bc = (PeriodicBC(), (NeumannBC(), DirichletBC()))
bc = PeriodicBC()
bc = NeumannBC()
```
Example that should error:
```julia
bc = ((PeriodicBC(), DirichletBC), ...) # error
```
- [x] Decide on what a boundary condition means when indices are out of bounds in more than one dimension #35 

### Documentation
- [x] General section on package usage, overview, etc @maltezfaria #36 
- [x] A section on `LevelSetTerm`
    - [x] Pour la courbure on peux se servir de la spirale #37 
    - [x] Advection term (done in #38)
- [x] Time integrators (done in #39)
- [x] Boundary conditions 
- [x] Extensions 
    - [x] Makie
    - [x] MMG #37
- [x] Examples
    - [x] Zalesak circle (WENO vs. upwind)
    - [x] Shape optimisation #37
    - [ ] Maybe Eikonal solver using reinitialisation (`v0.2.0`)
    - [ ] Shape optimisation using integral equations for Laplace problem (`v0.2.0`)

### Polish
- [ ] Remove dead code using `Codecov` once docs are written and coverage is setup to track docs (`v0.2.0`)
- [x] Clean `export`
- [x] Modify `Makie` recipe to use `contourf` to distinguish inside/outiside
- [x] Write the `_normalize_bc` function #35 

### Features
- [x] Utility to compute `volume` and `perimeter` of `LevelSet` #37

**Comment by maltezfaria** [comment]
Registration PR can be found here:

https://github.com/JuliaRegistries/General/pull/119346
